; Generated by scripts/generate-catalog.py; do not edit.
; Source: catalog/catalog.toml

_scheduled_catalog_table:
        .word   _scheduled_hello_descriptor
        .word   _scheduled_counter_descriptor
        .word   _scheduled_clock_descriptor
        .word   _scheduled_uptime_descriptor
        .word   _scheduled_embedded_hello_descriptor
        .word   _scheduled_embedded_ping_descriptor
        .word   _scheduled_shell_descriptor
        .word   0

_scheduled_hello_descriptor:
        .word   _scheduled_hello_name
        .word   0
        .word   _plsw_hello_trampoline
        .word   0
        .word   0
        .word   128
        .word   0
        .word   1
_scheduled_hello_name:
        .byte   104,101,108,108,111,0

_scheduled_counter_descriptor:
        .word   _scheduled_counter_name
        .word   0
        .word   _plsw_counter_trampoline
        .word   0
        .word   0
        .word   192
        .word   1
        .word   1
_scheduled_counter_name:
        .byte   99,111,117,110,116,101,114,0

_scheduled_clock_descriptor:
        .word   _scheduled_clock_name
        .word   0
        .word   _plsw_clock_trampoline
        .word   0
        .word   0
        .word   192
        .word   4
        .word   3
_scheduled_clock_name:
        .byte   99,108,111,99,107,0

_scheduled_uptime_descriptor:
        .word   _scheduled_uptime_name
        .word   0
        .word   _plsw_uptime_trampoline
        .word   0
        .word   0
        .word   192
        .word   4
        .word   3
_scheduled_uptime_name:
        .byte   117,112,116,105,109,101,0

_scheduled_embedded_hello_descriptor:
        .word   _scheduled_embedded_hello_name
        .word   1
        .word   _embedded_loader_trampoline
        .word   _embedded_embedded_hello_image
        .word   12
        .word   128
        .word   0
        .word   0
_scheduled_embedded_hello_name:
        .byte   101,109,98,101,100,100,101,100,45,104,101,108,108,111,0

_scheduled_embedded_ping_descriptor:
        .word   _scheduled_embedded_ping_name
        .word   1
        .word   _embedded_loader_trampoline
        .word   _embedded_embedded_ping_image
        .word   15
        .word   128
        .word   0
        .word   0
_scheduled_embedded_ping_name:
        .byte   101,109,98,101,100,100,101,100,45,112,105,110,103,0

_scheduled_shell_descriptor:
        .word   _scheduled_shell_name
        .word   2
        .word   _plsw_launcher_trampoline
        .word   0
        .word   0
        .word   256
        .word   6
        .word   15
_scheduled_shell_name:
        .byte   115,104,101,108,108,0

_block_catalog_index:
        .byte   7,1,83,87,84,120,104,179
        .byte   104,101,108,108,111,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        .byte   99,111,117,110,116,101,114,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
        .byte   99,108,111,99,107,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0
        .byte   117,112,116,105,109,101,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0
        .byte   101,109,98,101,100,100,101,100,45,104,101,108,108,111,0,0,4,0,0,0,0,0,0,0
        .byte   101,109,98,101,100,100,101,100,45,112,105,110,103,0,0,0,5,0,0,0,0,0,0,0
        .byte   115,104,101,108,108,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0
_block_catalog_index_end:

_SHELL_DF_TEXT:
        .byte   99,97,116,97,108,111,103,32,101,110,116,114,105,101,115,61,55,32,105,109,97,103,101,115,61,50,32,98,121,116,101,115,61,56,49,0
_SHELL_HELP_1:
        .byte   104,101,108,112,32,108,115,32,100,105,114,32,112,115,32,114,117,110,0
_SHELL_HELP_2:
        .byte   100,102,32,100,117,32,115,116,97,116,32,117,110,97,109,101,0
_SHELL_UNAME_TEXT:
        .byte   83,87,84,79,83,32,67,79,82,50,52,32,48,46,49,0
_SHELL_STAT_KIND:
        .byte   32,107,105,110,100,61,0
_SHELL_STAT_SOURCE:
        .byte   32,115,111,117,114,99,101,61,0
_SHELL_STAT_STACK:
        .byte   32,115,116,97,99,107,61,0
_SHELL_STAT_STATE:
        .byte   32,115,116,97,116,101,61,0
_SHELL_STAT_FLAGS:
        .byte   32,102,108,97,103,115,61,0
_SHELL_STAT_IMAGE:
        .byte   32,105,109,97,103,101,61,0
_SHELL_PROGRAM_TEXT:
        .byte   112,114,111,103,114,97,109,0
_SHELL_SERVICE_TEXT:
        .byte   115,101,114,118,105,99,101,0
_SHELL_RESIDENT_TEXT:
        .byte   114,101,115,105,100,101,110,116,0
_SHELL_EMBEDDED_TEXT:
        .byte   101,109,98,101,100,100,101,100,0
_SHELL_DU_TEXT_0:
        .byte   101,109,98,101,100,100,101,100,45,104,101,108,108,111,32,51,54,32,98,121,116,101,115,0
_SHELL_DU_TEXT_1:
        .byte   101,109,98,101,100,100,101,100,45,112,105,110,103,32,52,53,32,98,121,116,101,115,0
