; Generated by scripts/generate-catalog.py; do not edit.
; Source: catalog/catalog.toml

_scheduled_catalog_table:
        .word   _scheduled_hello_descriptor
        .word   _scheduled_counter_descriptor
        .word   _scheduled_clock_descriptor
        .word   _scheduled_embedded_hello_descriptor
        .word   _scheduled_shell_descriptor
        .word   0

_scheduled_hello_descriptor:
        .word   _scheduled_hello_name
        .word   0
        .word   _plsw_hello_trampoline
        .word   0
        .word   0
        .word   128
        .word   0
        .word   1
_scheduled_hello_name:
        .byte   104,101,108,108,111,0

_scheduled_counter_descriptor:
        .word   _scheduled_counter_name
        .word   0
        .word   _plsw_counter_trampoline
        .word   0
        .word   0
        .word   192
        .word   1
        .word   1
_scheduled_counter_name:
        .byte   99,111,117,110,116,101,114,0

_scheduled_clock_descriptor:
        .word   _scheduled_clock_name
        .word   0
        .word   _plsw_clock_trampoline
        .word   0
        .word   0
        .word   192
        .word   4
        .word   3
_scheduled_clock_name:
        .byte   99,108,111,99,107,0

_scheduled_embedded_hello_descriptor:
        .word   _scheduled_embedded_hello_name
        .word   1
        .word   _embedded_loader_trampoline
        .word   _embedded_embedded_hello_image
        .word   12
        .word   128
        .word   0
        .word   0
_scheduled_embedded_hello_name:
        .byte   101,109,98,101,100,100,101,100,45,104,101,108,108,111,0

_scheduled_shell_descriptor:
        .word   _scheduled_shell_name
        .word   2
        .word   _plsw_launcher_trampoline
        .word   0
        .word   0
        .word   256
        .word   4
        .word   15
_scheduled_shell_name:
        .byte   115,104,101,108,108,0
