#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TOOL_DIR="$ROOT_DIR/tools/bin"
PLSW_SOURCE="${1:-$ROOT_DIR/tests/catalog-counter.plsw}"
BUILD_NAME="${2:-catalog-spawn}"
PROVIDER_MODE="${3:-memory}"
CATALOG_MANIFEST="${4:-$ROOT_DIR/catalog/catalog.toml}"
OUT_DIR="$ROOT_DIR/build/$BUILD_NAME"
ASM="$TOOL_DIR/cor24-asm"
EMU="$ROOT_DIR/scripts/swtos-emu"
META_GEN="$TOOL_DIR/meta-gen"
LINK="$TOOL_DIR/link24"
PLSW="$ROOT_DIR/tools/plsw.lgo"
MODULES=(kernel protocol app)

# Generated modules are concatenations and compiler output that live under
# build/. Without this banner build/*/kernel.raw.s opens with the header of
# hal/cor24/catalog-spawn.s and reads exactly like the tracked kernel source,
# so an edit made while debugging is silently discarded by the next build.
generated_banner() {
    printf '; Generated by scripts/catalog-spawn-link.sh; do not edit.\n'
    printf '; Source: %s\n\n' "$1"
}

mkdir -p "$OUT_DIR"
if [ "$CATALOG_MANIFEST" = "$ROOT_DIR/catalog/catalog.toml" ]; then
    python3 "$ROOT_DIR/scripts/generate-catalog.py"
    SCHEDULED_CATALOG="$ROOT_DIR/hal/cor24/catalog_generated.s"
    SHELL_CATALOG="$ROOT_DIR/include/shell_catalog_generated.msw"
else
    SCHEDULED_CATALOG="$OUT_DIR/catalog_generated.s"
    python3 "$ROOT_DIR/scripts/generate-catalog.py" \
        --manifest "$CATALOG_MANIFEST" \
        --output "$OUT_DIR/catalog_generated.msw" \
        --scheduled-output "$SCHEDULED_CATALOG" \
        --shell-output "$OUT_DIR/shell_catalog_generated.msw"
    SHELL_CATALOG="$OUT_DIR/shell_catalog_generated.msw"
fi
scratch=$(mktemp -d /tmp/swtos-catalog-spawn-XXXXXX)
trap 'rm -rf "$scratch"' EXIT
{
    printf 'c\n'
    if [ "$(basename "$PLSW_SOURCE")" = "catalog-shell.plsw" ]; then
        sed -n 'p' "$SHELL_CATALOG"
    fi
    sed -n 'p' "$PLSW_SOURCE"
    printf '\x04'
} > "$scratch/input.bin"

# The compiler is a COR24 program, so it runs under an instruction budget, and
# the budget has to grow with the source it compiles. This one passed half a
# billion in September 2026. PLSW_BUDGET can be set lower to prove the check
# below still catches a truncated compile.
PLSW_BUDGET=${PLSW_BUDGET:-2000000000}
compiler_output=$($EMU --lgo "$PLSW" --uart-file "$scratch/input.bin" \
    --quiet --speed 0 -n "$PLSW_BUDGET" -t 600 2>&1)
# Here-strings, not a pipe. Under `set -o pipefail`, `echo "$x" | grep -q p`
# reports failure when the pattern IS found: grep exits at the first match and
# closes the pipe, echo dies with EPIPE, and pipefail takes echo's status for
# the pipeline. That inverts every test below -- a real compile error would be
# read as a clean compile, and a complete compile as a truncated one.
if grep -q 'compilation failed\|COMPILE ERROR\|ERROR:' <<<"$compiler_output"; then
    echo "PL/SW task compilation failed:" >&2
    echo "$compiler_output" >&2
    exit 1
fi
# A compiler that runs out of instructions stops mid-emit, and the half-written
# assembly it leaves behind is not obviously half-written: it fails much later
# as an undefined label, at whatever line the emit happened to stop on, which
# reads like a fault in the source that was being compiled.
# The compiler brackets its assembly, and the closing marker is the only thing
# that says it finished. A compile that stops early -- out of instructions, out
# of wall clock, halted -- stops mid-emit, and the half-written assembly it
# leaves behind is not obviously half-written: it fails much later as an
# undefined label, at whatever line the emit happened to stop on, which reads
# like a fault in the source being compiled rather than a truncated file.
#
# Asking whether it finished beats asking why it might not have. An earlier
# version of this check compared the instruction count against the budget,
# which reported a clean compile as a failure the first time one finished just
# over the old ceiling.
if ! grep -q -- '--- end assembly ---' <<<"$compiler_output"; then
    echo "PL/SW compilation did not finish: no end-of-assembly marker." >&2
    echo "Its output is truncated, so the build would fail later as an" >&2
    echo "undefined label. If it ran out of instructions, raise PLSW_BUDGET" >&2
    echo "(currently $PLSW_BUDGET) in $0." >&2
    echo "$compiler_output" | tail -3 >&2
    exit 1
fi
generated_banner "$PLSW_SOURCE compiled by tools/plsw.lgo" \
    > "$OUT_DIR/app.raw.s"
echo "$compiler_output" | sed -n \
    '/--- generated assembly ---/,/--- end assembly ---/{/--- generated assembly ---/d;/--- end assembly ---/d;p;}' \
    >> "$OUT_DIR/app.raw.s"
printf '%s\n' \
    '        .globl  _swtos_image_end' \
    '_swtos_image_end:' \
    '        .byte   0' >> "$OUT_DIR/app.raw.s"
generated_banner "hal/cor24/{catalog-spawn,preemption,i2c,spi}.s, the generated catalog table, and each cataloged image" \
    > "$OUT_DIR/kernel.raw.s"
sed -n 'p' "$ROOT_DIR/hal/cor24/catalog-spawn.s" >> "$OUT_DIR/kernel.raw.s"
sed -n 'p' "$ROOT_DIR/hal/cor24/preemption.s" >> "$OUT_DIR/kernel.raw.s"
generated_banner "hal/cor24/protocol-v1.s" > "$OUT_DIR/protocol.raw.s"
sed -n 'p' "$ROOT_DIR/hal/cor24/protocol-v1.s" >> "$OUT_DIR/protocol.raw.s"
sed -n 'p' "$ROOT_DIR/hal/cor24/i2c.s" >> "$OUT_DIR/kernel.raw.s"
sed -n 'p' "$ROOT_DIR/hal/cor24/spi.s" >> "$OUT_DIR/kernel.raw.s"
sed -n 'p' "$SCHEDULED_CATALOG" >> "$OUT_DIR/kernel.raw.s"
while IFS=$'\t' read -r image_name image_manifest; do
    image_label="${image_name//-/_}"
    image_asm="$OUT_DIR/$image_name.s"
    python3 "$ROOT_DIR/scripts/cor24-image.py" emit-asm \
        "$ROOT_DIR/$image_manifest" "$image_asm" \
        --label "_embedded_${image_label}_image"
    sed -n 'p' "$image_asm" >> "$OUT_DIR/kernel.raw.s"
done < <(python3 "$ROOT_DIR/scripts/generate-catalog.py" \
    --manifest "$CATALOG_MANIFEST" --list-images)
python3 "$ROOT_DIR/scripts/configure-provider.py" \
    "$OUT_DIR/kernel.raw.s" "$PROVIDER_MODE"

sizes=()
for module in "${MODULES[@]}"; do
    "$META_GEN" prep "$OUT_DIR/$module.raw.s" \
        -o "$OUT_DIR/$module.s" --syms "$OUT_DIR/$module.syms"
    "$ASM" "$OUT_DIR/$module.s" -o "$OUT_DIR/$module.lgo" \
        --bin "$OUT_DIR/$module.bin" --listing "$OUT_DIR/$module.lst"
    "$META_GEN" emit "$OUT_DIR/$module.lst" --syms "$OUT_DIR/$module.syms" \
        --module "$module" -o "$OUT_DIR/$module.meta"
    sizes+=("$(wc -c < "$OUT_DIR/$module.bin" | tr -d ' ')")
done

base=0
for i in "${!MODULES[@]}"; do
    module="${MODULES[$i]}"
    "$ASM" "$OUT_DIR/$module.s" --base-addr "$base" \
        -o "$OUT_DIR/$module.lgo" --bin "$OUT_DIR/$module.bin" \
        --listing "$OUT_DIR/$module.lst"
    base=$((base + sizes[i]))
done

"$LINK" --entry kernel --dir "$OUT_DIR" \
    --map "$OUT_DIR/program.map" kernel protocol app \
    -o "$OUT_DIR/program.bin"
python3 "$ROOT_DIR/scripts/generate-debug-info.py" \
    --binary "$OUT_DIR/program.bin" --map "$OUT_DIR/program.map" \
    --listing "$OUT_DIR/kernel.lst" --listing "$OUT_DIR/protocol.lst" \
    --listing "$OUT_DIR/app.lst" --output "$OUT_DIR/program.debug.json"
"$ROOT_DIR/scripts/cor24-bin-to-lgo.py" \
    "$OUT_DIR/program.bin" "$OUT_DIR/program.lgo" \
    --load-address 0 --entry-address 0
