#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TOOL_DIR="$ROOT_DIR/tools/bin"
PLSW_SOURCE="${1:-$ROOT_DIR/tests/catalog-counter.plsw}"
BUILD_NAME="${2:-catalog-spawn}"
PROVIDER_MODE="${3:-memory}"
CATALOG_MANIFEST="${4:-$ROOT_DIR/catalog/catalog.toml}"
OUT_DIR="$ROOT_DIR/build/$BUILD_NAME"
ASM="$TOOL_DIR/cor24-asm"
EMU="$ROOT_DIR/scripts/swtos-emu"
META_GEN="$TOOL_DIR/meta-gen"
LINK="$TOOL_DIR/link24"
PLSW="$ROOT_DIR/tools/plsw.lgo"
# app is last because _swtos_image_end is appended to it, and that symbol is
# where the heap and the stack arena begin. A module linked after it would sit
# above the marker and be overwritten by the first allocation -- which is what
# happened: the shell's own stack landed on the filesystem module's code, and
# the first call into it halted on whatever the stack had written there.
MODULES=(kernel protocol sdfs app)

# Generated modules are concatenations and compiler output that live under
# build/. Without this banner build/*/kernel.raw.s opens with the header of
# hal/cor24/catalog-spawn.s and reads exactly like the tracked kernel source,
# so an edit made while debugging is silently discarded by the next build.
generated_banner() {
    printf '; Generated by scripts/catalog-spawn-link.sh; do not edit.\n'
    printf '; Source: %s\n\n' "$1"
}

mkdir -p "$OUT_DIR"
if [ "$CATALOG_MANIFEST" = "$ROOT_DIR/catalog/catalog.toml" ]; then
    python3 "$ROOT_DIR/scripts/generate-catalog.py"
    SCHEDULED_CATALOG="$ROOT_DIR/hal/cor24/catalog_generated.s"
    SHELL_CATALOG="$ROOT_DIR/include/shell_catalog_generated.msw"
else
    SCHEDULED_CATALOG="$OUT_DIR/catalog_generated.s"
    python3 "$ROOT_DIR/scripts/generate-catalog.py" \
        --manifest "$CATALOG_MANIFEST" \
        --output "$OUT_DIR/catalog_generated.msw" \
        --scheduled-output "$SCHEDULED_CATALOG" \
        --shell-output "$OUT_DIR/shell_catalog_generated.msw"
    SHELL_CATALOG="$OUT_DIR/shell_catalog_generated.msw"
fi
scratch=$(mktemp -d /tmp/swtos-catalog-spawn-XXXXXX)
trap 'rm -rf "$scratch"' EXIT

# The compiler is a COR24 program, so it runs under an instruction budget, and
# the budget has to grow with the source it compiles. This one passed half a
# billion in September 2026. PLSW_BUDGET can be set lower to prove the
# truncation check below still catches a half-written compile.
PLSW_BUDGET=${PLSW_BUDGET:-2000000000}

# Compile one .plsw into one .raw.s. One invocation per source, which is the
# point: the compiler's symbol table is per compilation, so splitting a source
# in two gives each half its own table, and link24 resolves across them by name
# afterwards.
compile_plsw() {
    local source="$1" output="$2" banner="$3" prefix="$4"
    local input out
    input="$scratch/$(basename "$source").bin"
    {
        printf 'c\n'
        if [ -n "$prefix" ]; then
            sed -n 'p' "$prefix"
        fi
        sed -n 'p' "$source"
        printf '\x04'
    } > "$input"

    out=$($EMU --lgo "$PLSW" --uart-file "$input" \
        --quiet --speed 0 -n "$PLSW_BUDGET" -t 600 2>&1)

    # Here-strings, not pipes: under `set -o pipefail`, `echo "$x" | grep -q p`
    # reports failure when the pattern IS found, because grep exits at the
    # first match, echo dies with EPIPE, and pipefail takes echo's status.
    if grep -q 'compilation failed\|COMPILE ERROR\|ERROR:' <<<"$out"; then
        echo "PL/SW compilation failed for $source:" >&2
        echo "$out" >&2
        exit 1
    fi
    # The closing marker is the only thing that says the compiler finished. A
    # compile that stops early leaves assembly that is not obviously
    # half-written: it fails much later as an undefined label, at whatever line
    # the emit stopped on, which reads like a fault in the source.
    if ! grep -q -- '--- end assembly ---' <<<"$out"; then
        echo "PL/SW compilation of $source did not finish: no end-of-assembly" >&2
        echo "marker, so its output is truncated. If it ran out of instructions," >&2
        echo "raise PLSW_BUDGET (currently $PLSW_BUDGET) in $0." >&2
        tail -3 <<<"$out" >&2
        exit 1
    fi
    generated_banner "$banner" > "$output"
    sed -n '/--- generated assembly ---/,/--- end assembly ---/{/--- generated assembly ---/d;/--- end assembly ---/d;p;}' \
        <<<"$out" >> "$output"
}

if [ "$(basename "$PLSW_SOURCE")" = "catalog-shell.plsw" ]; then
    compile_plsw "$PLSW_SOURCE" "$OUT_DIR/app.raw.s" \
        "$PLSW_SOURCE compiled by tools/plsw.lgo" "$SHELL_CATALOG"
    compile_plsw "$ROOT_DIR/tests/catalog-sdfs.plsw" "$OUT_DIR/sdfs.raw.s" \
        "tests/catalog-sdfs.plsw compiled by tools/plsw.lgo" ""
else
    compile_plsw "$PLSW_SOURCE" "$OUT_DIR/app.raw.s" \
        "$PLSW_SOURCE compiled by tools/plsw.lgo" ""
    generated_banner "no filesystem module for $PLSW_SOURCE" > "$OUT_DIR/sdfs.raw.s"
fi
printf '%s\n' \
    '        .globl  _swtos_image_end' \
    '_swtos_image_end:' \
    '        .byte   0' >> "$OUT_DIR/app.raw.s"
generated_banner "hal/cor24/{catalog-spawn,preemption,i2c,spi}.s, the generated catalog table, and each cataloged image" \
    > "$OUT_DIR/kernel.raw.s"
sed -n 'p' "$ROOT_DIR/hal/cor24/catalog-spawn.s" >> "$OUT_DIR/kernel.raw.s"
sed -n 'p' "$ROOT_DIR/hal/cor24/preemption.s" >> "$OUT_DIR/kernel.raw.s"
generated_banner "hal/cor24/protocol-v1.s" > "$OUT_DIR/protocol.raw.s"
sed -n 'p' "$ROOT_DIR/hal/cor24/protocol-v1.s" >> "$OUT_DIR/protocol.raw.s"
sed -n 'p' "$ROOT_DIR/hal/cor24/i2c.s" >> "$OUT_DIR/kernel.raw.s"
sed -n 'p' "$ROOT_DIR/hal/cor24/spi.s" >> "$OUT_DIR/kernel.raw.s"
sed -n 'p' "$SCHEDULED_CATALOG" >> "$OUT_DIR/kernel.raw.s"
while IFS=$'\t' read -r image_name image_manifest; do
    image_label="${image_name//-/_}"
    image_asm="$OUT_DIR/$image_name.s"
    python3 "$ROOT_DIR/scripts/cor24-image.py" emit-asm \
        "$ROOT_DIR/$image_manifest" "$image_asm" \
        --label "_embedded_${image_label}_image"
    sed -n 'p' "$image_asm" >> "$OUT_DIR/kernel.raw.s"
done < <(python3 "$ROOT_DIR/scripts/generate-catalog.py" \
    --manifest "$CATALOG_MANIFEST" --list-images)
python3 "$ROOT_DIR/scripts/configure-provider.py" \
    "$OUT_DIR/kernel.raw.s" "$PROVIDER_MODE"

sizes=()
for module in "${MODULES[@]}"; do
    "$META_GEN" prep "$OUT_DIR/$module.raw.s" \
        -o "$OUT_DIR/$module.s" --syms "$OUT_DIR/$module.syms"
    "$ASM" "$OUT_DIR/$module.s" -o "$OUT_DIR/$module.lgo" \
        --bin "$OUT_DIR/$module.bin" --listing "$OUT_DIR/$module.lst"
    "$META_GEN" emit "$OUT_DIR/$module.lst" --syms "$OUT_DIR/$module.syms" \
        --module "$module" -o "$OUT_DIR/$module.meta"
    sizes+=("$(wc -c < "$OUT_DIR/$module.bin" | tr -d ' ')")
done

base=0
for i in "${!MODULES[@]}"; do
    module="${MODULES[$i]}"
    "$ASM" "$OUT_DIR/$module.s" --base-addr "$base" \
        -o "$OUT_DIR/$module.lgo" --bin "$OUT_DIR/$module.bin" \
        --listing "$OUT_DIR/$module.lst"
    base=$((base + sizes[i]))
done

"$LINK" --entry kernel --dir "$OUT_DIR" \
    --map "$OUT_DIR/program.map" kernel protocol sdfs app \
    -o "$OUT_DIR/program.bin"
python3 "$ROOT_DIR/scripts/generate-debug-info.py" \
    --binary "$OUT_DIR/program.bin" --map "$OUT_DIR/program.map" \
    --listing "$OUT_DIR/kernel.lst" --listing "$OUT_DIR/protocol.lst" \
    --listing "$OUT_DIR/app.lst" --listing "$OUT_DIR/sdfs.lst" \
    --output "$OUT_DIR/program.debug.json"
"$ROOT_DIR/scripts/cor24-bin-to-lgo.py" \
    "$OUT_DIR/program.bin" "$OUT_DIR/program.lgo" \
    --load-address 0 --entry-address 0
