#!/usr/bin/env python3
"""Verify every generated source carries a do-not-edit banner.

Generated sources are indistinguishable from hand-written ones once they are
open in an editor, and several of them are concatenations that begin with a
tracked file's own header. Each must therefore declare itself on its first
line and name the script that produced it, so an accidental edit is obvious
before the next build discards it.

Tracked outputs must exist. Build outputs are checked wherever they are
present, so this runs meaningfully both before and after a full build.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Generated sources committed to the repository. Each must exist.
TRACKED = (
    "include/catalog_generated.msw",
    "include/shell_catalog_generated.msw",
    "hal/cor24/catalog_generated.s",
)

# Generated sources under build/. Every match is checked; none is required,
# because which ones exist depends on the recipes that have run.
BUILD_GLOBS = (
    "build/*.s",
    "build/*/app.raw.s",
    "build/*/kernel.raw.s",
    "build/*/protocol.raw.s",
    "build/*/kernel.s",
    "build/*/protocol.s",
    "build/*/app.s",
    "build/*/catalog_generated.s",
    "build/*/cpu-hog.s",
    "build/*/embedded-hello.s",
    "build/*/embedded-ping.s",
)

# "; Generated by scripts/x.sh; do not edit." or the /* */ spelling.
BANNER = re.compile(
    r"^\s*(?:;|/\*)\s*Generated by (?P<script>\S+?);\s*do not edit\.", re.IGNORECASE
)


def check(path: pathlib.Path, failures: list) -> None:
    try:
        first = path.read_text(errors="replace").splitlines()[:1]
    except OSError as error:
        failures.append(f"{path.relative_to(ROOT)}: unreadable ({error})")
        return
    if not first:
        failures.append(f"{path.relative_to(ROOT)}: empty, no generated banner")
        return
    match = BANNER.match(first[0])
    if not match:
        failures.append(
            f"{path.relative_to(ROOT)}: first line is not a generated banner\n"
            f"    found: {first[0][:78]!r}\n"
            f"    want:  '; Generated by <script>; do not edit.'"
        )
        return
    script = ROOT / match.group("script")
    if not script.exists():
        failures.append(
            f"{path.relative_to(ROOT)}: banner names {match.group('script')}, "
            "which does not exist"
        )


def main() -> int:
    failures: list[str] = []
    checked = 0

    for relative in TRACKED:
        path = ROOT / relative
        if not path.exists():
            failures.append(f"{relative}: missing; regenerate with just catalog-generate")
            continue
        check(path, failures)
        checked += 1

    # A new committed *_generated.* source must be declared above, so that it
    # cannot silently escape this check.
    declared = {ROOT / relative for relative in TRACKED}
    for path in sorted(ROOT.glob("**/*_generated.*")):
        if "build" in path.relative_to(ROOT).parts or path in declared:
            continue
        failures.append(
            f"{path.relative_to(ROOT)}: looks generated but is not listed in "
            f"{pathlib.Path(__file__).name} TRACKED"
        )

    for pattern in BUILD_GLOBS:
        for path in sorted(ROOT.glob(pattern)):
            check(path, failures)
            checked += 1

    if failures:
        print("FAIL: generated sources missing a do-not-edit banner", file=sys.stderr)
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        return 1

    print(f"PASS: {checked} generated sources declare their generator")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
