#!/usr/bin/env python3
"""Generate the SWTOS PL/SW resident catalog from TOML."""

import argparse
import re
import sys
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = ROOT / "catalog" / "catalog.toml"
DEFAULT_OUTPUT = ROOT / "include" / "catalog_generated.msw"
DEFAULT_SCHEDULED_OUTPUT = ROOT / "hal" / "cor24" / "catalog_generated.s"
NAME_PATTERN = re.compile(r"[a-z][a-z0-9-]*\Z")
ENTRY_PATTERN = re.compile(r"[A-Z_][A-Z0-9_]*\Z")
SCHEDULED_ENTRY_PATTERN = re.compile(r"_[A-Za-z_][A-Za-z0-9_]*\Z")
KINDS = {"program": "IMAGE_PROGRAM", "service": "IMAGE_SERVICE"}
FLAGS = {
    "resident": ("IMAGE_RESIDENT", 1),
    "single_instance": ("IMAGE_SINGLE_INST", 2),
    "privileged": ("IMAGE_PRIVILEGED", 4),
    "autostart": ("IMAGE_AUTOSTART", 8),
    "restartable": ("IMAGE_RESTARTABLE", 16),
    "read_only": ("IMAGE_READ_ONLY", 32),
}
ENTRY_KEYS = {"name", "entry", "scheduled_entry", "stack_words", "state_words", "flags"}


def fail(message: str) -> None:
    raise ValueError(message)


def load_entries(path: Path) -> list[dict]:
    with path.open("rb") as stream:
        document = tomllib.load(stream)
    unknown_sections = set(document) - set(KINDS)
    if unknown_sections:
        fail(f"unknown manifest section: {sorted(unknown_sections)[0]}")

    entries = []
    names = set()
    for section, kind in KINDS.items():
        values = document.get(section, [])
        if not isinstance(values, list):
            fail(f"{section} must be an array of tables")
        for index, value in enumerate(values):
            label = f"{section}[{index}]"
            if not isinstance(value, dict):
                fail(f"{label} must be a table")
            unknown_keys = set(value) - ENTRY_KEYS
            if unknown_keys:
                fail(f"{label} has unknown key: {sorted(unknown_keys)[0]}")
            missing_keys = ENTRY_KEYS - set(value)
            if missing_keys:
                fail(f"{label} is missing: {sorted(missing_keys)[0]}")

            name = value["name"]
            entry = value["entry"]
            scheduled_entry = value["scheduled_entry"]
            stack_words = value["stack_words"]
            state_words = value["state_words"]
            flags = value["flags"]
            if not isinstance(name, str) or not NAME_PATTERN.fullmatch(name):
                fail(f"{label} has invalid name")
            if name in names:
                fail(f"duplicate catalog name: {name}")
            names.add(name)
            if not isinstance(entry, str) or not ENTRY_PATTERN.fullmatch(entry):
                fail(f"{label} has invalid entry symbol")
            if not isinstance(scheduled_entry, str) or not SCHEDULED_ENTRY_PATTERN.fullmatch(scheduled_entry):
                fail(f"{label} has invalid scheduled entry symbol")
            if not isinstance(stack_words, int) or isinstance(stack_words, bool) or stack_words <= 0:
                fail(f"{label} stack_words must be a positive integer")
            if not isinstance(state_words, int) or isinstance(state_words, bool) or state_words < 0:
                fail(f"{label} state_words must be a nonnegative integer")
            if not isinstance(flags, list) or not all(isinstance(flag, str) for flag in flags):
                fail(f"{label} flags must be an array of strings")
            unknown_flags = set(flags) - set(FLAGS)
            if unknown_flags:
                fail(f"{label} has unknown flag: {sorted(unknown_flags)[0]}")
            if len(flags) != len(set(flags)):
                fail(f"{label} has duplicate flags")

            entries.append(
                {
                    "name": name,
                    "entry": entry,
                    "scheduled_entry": scheduled_entry,
                    "kind": kind,
                    "stack_words": stack_words,
                    "state_words": state_words,
                    "flags": flags,
                }
            )
    if not entries:
        fail("catalog must contain at least one program or service")
    return entries


def render(entries: list[dict], manifest: Path) -> str:
    lines = [
        "/* Generated by scripts/generate-catalog.py; do not edit. */",
        f"/* Source: {manifest.relative_to(ROOT)} */",
        "",
        "%DEFINE CATALOG_DESC_WORDS 8;",
        f"%DEFINE CATALOG_COUNT {len(entries)};",
        f"DCL CATALOG_TABLE({len(entries) * 8}) INT;",
        "",
    ]
    for index, entry in enumerate(entries):
        size = len(entry["name"]) + 1
        lines.append(f"DCL CATALOG_NAME_{index}({size}) CHAR INIT('{entry['name']}');")
    lines.extend(["", "CATALOG_INIT: PROC;"])
    for index, entry in enumerate(entries):
        offset = index * 8
        flag_value = sum(FLAGS[flag][1] for flag in entry["flags"])
        lines.extend(
            [
                f"    CATALOG_TABLE({offset}) = ADDR(CATALOG_NAME_{index});",
                f"    CATALOG_TABLE({offset + 1}) = {entry['kind']};",
                f"    CATALOG_TABLE({offset + 2}) = 0;",
                f"    CATALOG_TABLE({offset + 3}) = 0;",
                f"    CATALOG_TABLE({offset + 4}) = 0;",
                f"    CATALOG_TABLE({offset + 5}) = {entry['stack_words']};",
                f"    CATALOG_TABLE({offset + 6}) = {entry['state_words']};",
                f"    CATALOG_TABLE({offset + 7}) = {flag_value};",
            ]
        )
    lines.extend(["    ASM DO;", "        'la      r2,_CATALOG_TABLE';"])
    for index, entry in enumerate(entries):
        byte_offset = index * 24 + 6
        lines.extend(
            [
                f"        'la      r0,_{entry['entry']}';",
                f"        'sw      r0,{byte_offset}(r2)';",
            ]
        )
    lines.extend(["    END;", "END;", ""])
    return "\n".join(lines)


def render_scheduled(entries: list[dict], manifest: Path) -> str:
    lines = [
        "; Generated by scripts/generate-catalog.py; do not edit.",
        f"; Source: {manifest.relative_to(ROOT)}",
        "",
        "_scheduled_catalog_table:",
    ]
    for entry in entries:
        label = entry["name"].replace("-", "_")
        lines.append(f"        .word   _scheduled_{label}_descriptor")
    lines.append("")
    for entry in entries:
        label = entry["name"].replace("-", "_")
        flag_value = sum(FLAGS[flag][1] for flag in entry["flags"])
        kind_value = 0 if entry["kind"] == "IMAGE_PROGRAM" else 2
        name_bytes = ",".join(str(byte) for byte in entry["name"].encode("ascii"))
        lines.extend(
            [
                f"_scheduled_{label}_descriptor:",
                f"        .word   _scheduled_{label}_name",
                f"        .word   {kind_value}",
                f"        .word   {entry['scheduled_entry']}",
                "        .word   0",
                "        .word   0",
                f"        .word   {entry['stack_words']}",
                f"        .word   {entry['state_words']}",
                f"        .word   {flag_value}",
                f"_scheduled_{label}_name:",
                f"        .byte   {name_bytes},0",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--scheduled-output", type=Path, default=DEFAULT_SCHEDULED_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        entries = load_entries(args.manifest)
        rendered = render(entries, args.manifest)
        scheduled_rendered = render_scheduled(entries, args.manifest)
    except (OSError, tomllib.TOMLDecodeError, ValueError) as error:
        print(f"catalog generation failed: {error}", file=sys.stderr)
        return 1

    if args.check:
        try:
            current = args.output.read_text()
            scheduled_current = args.scheduled_output.read_text()
        except OSError as error:
            print(f"catalog check failed: {error}", file=sys.stderr)
            return 1
        if current != rendered or scheduled_current != scheduled_rendered:
            print("catalog check failed: regenerate catalog outputs", file=sys.stderr)
            return 1
        print(f"PASS: catalog is current ({len(load_entries(args.manifest))} entries)")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    args.scheduled_output.parent.mkdir(parents=True, exist_ok=True)
    args.scheduled_output.write_text(scheduled_rendered)
    print(f"Generated {len(entries)} entries -> {args.output}, {args.scheduled_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
